#!/bin/bash
#SBATCH --job-name=assignment1_parallel
#SBATCH --output=assignment1_parallel_output.txt
#SBATCH --error=assignment1_error.txt
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:10:00
#SBATCH --mem=4GB

# Load the necessary module for GCC
module load gcc

# Compile the C++ code
g++ -o assignment1_parallel assignment1_parallel.cpp -fopenmp

# Run the executable
./assignment1_parallel

# Print job done message
echo "Job done"