#!/bin/bash
#SBATCH --job-name=bloom_filter
#SBATCH --output=assignment1_output.txt
#SBATCH --error=assignment1_error.txt
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:10:00
#SBATCH --mem=4GB

# Load the necessary module for GCC
module load gcc

# Compile the C++ code
g++ -o assignment1 assignment1.cpp -fopenmp

# Run the executable
./assignment1

# Print job done message
echo "Job done"